boards: maix-bit: Update README.txt with updated clone path
Update apps clone path to avoid below error seen due to
expected relative path.

tools/Makefile.unix:329: recipe for target 'dirlinks' failed
make: *** [dirlinks] Error 2
ERROR: failed to refresh

Signed-off-by: Govind Singh <govind.sk85@gmail.com>