fix the compilation error caused by 'DEBUGASSERT'
error: implicit declaration of function 'DEBUGASSERT' [-Werror=implicit-function-declaration]

Signed-off-by: v-tangmeng <v-tangmeng@xiaomi.com>