arch/arm: fix compile error.
Since mii_ioctl_data_s.val_out has been changed from uint16_t to uint32_t, the type of the passed function needs to be changed

chip/kinetis_enet.c: In function 'kinetis_ioctl':
chip/kinetis_enet.c:1354:33: error: passing argument 4 of 'kinetis_readmii' from incompatible pointer type [-Werror=incompatible-pointer-types]
 1354 |                                 &req->val_out);
      |                                 ^~~~~~~~~~~~~
      |                                 |
      |                                 uint32_t * {aka long unsigned int *}
chip/kinetis_enet.c:315:41: note: expected 'uint16_t *' {aka 'short unsigned int *'} but argument is of type 'uint32_t *' {aka 'long unsigned int *'}
  315 |              uint8_t regaddr, uint16_t *data);
      |                               ~~~~~~~~~~^~~~

Signed-off-by: wangzhi16 <wangzhi16@xiaomi.com>