include/percpu: move up_this_cpu from arch.h to percpu.h
Fix the depency issue of up_this_cpu
Causing link issue: undefined reference to `up_this_cpu'

Signed-off-by: buxiasen <buxiasen@xiaomi.com>