arch/arm: Fix compile error
chip/efm32_leserial.c: In function 'efm32_restoreuartint':
 chip/efm32_leserial.c:327:37: error: 'len' undeclared (first use in this function); did you mean 'ien'?
 327 | efm32_restoreuartint_nolock(priv, len);
 | ^~~
 | ien
 chip/efm32_leserial.c:327:37: note: each undeclared identifier is reported only once for each function it appears in
 make[1]: *** [Makefile:168: efm32_leserial.o] Error 1
 make[1]: Target 'libarch.a' not remade because of errors.
 make: *** [tools/LibTargets.mk:170: arch/arm/src/libarch.a] Error 2
 make: Target 'all' not remade because of errors.
 /home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/nuttx/tools/testbuild.sh: line 385: /home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/nuttx/../nuttx/nuttx.manifest: No such file or directory
 Normalize efm32gg-stk3700/nsh

Signed-off-by: wangzhi16 <wangzhi16@xiaomi.com>