arch/tricore: change PRIuPTR to lu
Fixed the modlib build issue:
nuttx/libs/libc/modlib/modlib_bind.c:365:20: error:
format '%u' expects argument of type 'unsigned int',
but argument 5 has type 'long unsigned int'.

Signed-off-by: zhangyuan29 <zhangyuan29@xiaomi.com>