xtensa: fix compile error
Espressif HAL for 3rd Party Platforms: e3899a2324c8e326db20f99f208e890fdd7a5b92
CC:  vfs/fs_statfs.c In file included from chip/esp32s3_libc_stubs.c:25:
chip/esp32s3_libc_stubs.c: In function 'esp_setup_syscall_table':
chip/esp32s3_libc_stubs.c:418:3: error: static assertion failed: "Invalid size of struct __lock"
  418 |   static_assert(sizeof(struct __lock) >= sizeof(mutex_t),

sizeof(struct __lock) 16
sizeof(mutex_t) 20 cause by 9225d47b62cb6c3ef62d891e1830341dbfa875ab

Signed-off-by: hujun5 <hujun5@xiaomi.com>