Reapply "sim: disable asan check for hostirq"
This reverts commit add284e80be568d4fb159b9028cc7a5878618cf0.

If no this patch, asan will report error:

ERROR: AddressSanitizer: stack-buffer-underflow on address 0xe5c4e750 at pc 0xed4f4108 bp 0xe5c4e698 sp 0xe5c4e26c
WRITE of size 128 at 0xe5c4e750 thread T0
    #0 0xed4f4107 in __interceptor_sigemptyset ../../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4317
    #1 0x4611c380 in up_irq_restore ~/nuttx/arch/sim/src/sim/posix/sim_hostirq.c:117
    #2 0x466ab539 in pre_start ~/nuttx/arch/sim/src/sim/sim_initialstate.c:49

0xe5c4e750 is located 73552 bytes inside of 73728-byte region [0xe5c3c800,0xe5c4e800)
allocated by thread T0 here:
    #0 0xed585f3f in __interceptor_posix_memalign ../../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x4611d3e9 in host_memalign ~/nuttx/arch/sim/src/sim/posix/sim_hostmemory.c:156
    #2 0x4611d669 in host_realloc ~/nuttx/arch/sim/src/sim/posix/sim_hostmemory.c:181
    #3 0x466b04c1 in mm_realloc ~/nuttx/arch/sim/src/sim/sim_heap.c:396
    #4 0x466b0090 in mm_malloc ~/nuttx/arch/sim/src/sim/sim_heap.c:313
    #5 0x463fdaa1 in malloc ~/nuttx/mm/umm_heap/umm_malloc.c:66
    #6 0x466ac94c in up_create_stack ~/nuttx/arch/sim/src/sim/sim_createstack.c:120
    #7 0x466233cd in nxtask_init ~/nuttx/sched/task/task_init.c:189
    #8 0x46622176 in nxthread_create ~/nuttx/sched/task/task_create.c:108
    #9 0x46622494 in nxtask_create ~/nuttx/sched/task/task_create.c:172
    #10 0x4662254c in task_create_with_stack ~/nuttx/sched/task/task_create.c:213
    #11 0x466226e6 in task_create ~/nuttx/sched/task/task_create.c:227
    #12 0x47bccbc0 in restart_test ~/apps/testing/ostest/restart.c:181
    #13 0x47bbff98 in user_main ~/apps/testing/ostest/ostest_main.c:361
    #14 0x46a86464 in nxtask_startup ~/nuttx/libs/libc/sched/task_startup.c:72
    #15 0x466294c7 in nxtask_start ~/nuttx/sched/task/task_start.c:104
    #16 0x466ab61b in pre_start ~/nuttx/arch/sim/src/sim/sim_initialstate.c:53

Signed-off-by: buxiasen <buxiasen@xiaomi.com>