freedom-k64f/demo: Support Ethernet
It was tested using:

  nsh> ifconfig
  eth0    Link encap:Ethernet HWaddr 52:13:FF:FF:FF:FF at DOWN
          inet addr:10.0.0.2 DRaddr:10.0.0.1 Mask:255.255.255.0

All flags are needed to prevent build failures like:

    chip/kinetis_enet.c:181:4:\
    error: #error "Unrecognized or missing PHY selection"

    netlib_setifstatus.c: In function 'netlib_ifup':
    netlib_setifstatus.c:83:27: \
    error: 'NETLIB_SOCK_TYPE' undeclared (first use in this function);

Change-Id: I9496528ae09f6244d73ab77dbcd307ced95f46fd
Bug: https://github.com/apache/incubator-nuttx/pull/1988
Forwarded: https://github.com/apache/incubator-nuttx/pull/2066
Signed-off-by: Philippe Coval <rzr@users.sf.net>