arch/intel64_cpustart.c add missing spinlock include
fixes gcc 14 error:

chip/intel64_cpustart.c:88:3: error: implicit declaration of function ‘SP_DMB’ [-Wimplicit-function-declaration]
   88 |   SP_DMB();

Signed-off-by: p-szafonimateusz <p-szafonimateusz@xiaomi.com>