nrf91/serial: always compile nrf91_serial.c
So the up_putc function gets defined, just like most of other arch.

Fixed compile error:
./tools/configure.sh -l thingy91/nsh_rtt; make -j`nproc`

/home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/nuttx/arch/arm/src/common/arm_nputs.c:44: undefined reference to `up_putc'
 collect2: error: ld returned 1 exit status

Signed-off-by: wangzhi16 <wangzhi16@xiaomi.com>