sched/environ: fix compile error.
group/group_leave.c: In function 'group_release':
 /home/work/ssd1/workspace/Vela-Multi-Boards-dev-system-CI/nuttx/sched/environ/environ.h:39:32: error: statement with no effect [-Werror=unused-value]
 39 | # define env_release(group) (0)
 | ^
 group/group_leave.c:110:3: note: in expansion of macro 'env_release'
 110 | env_release(group);
 | ^~~~~~~~~~~
 cc1: all warnings being treated as errors
 make[1]: *** [Makefile:64: group_leave.o] Error 1
 make[1]: Target 'libsched.a' not remade because of errors.
 make: *** [tools/LibTargets.mk:71: sched/libsched.a] Error 2
 make: Target 'all' not remade because of errors.

Signed-off-by: wangzhi16 <wangzhi16@xiaomi.com>