arch/arm: fix compile error.
Building NuttX...
 chip/stm32_serial.c:562:23: error: expected expression before '=' token
 562 | .lock = = SP_UNLOCKED,
 | ^
 make[1]: *** [Makefile:168: stm32_serial.o] Error 1
 make[1]: Target 'libarch.a' not remade because of errors.
 make: *** [tools/LibTargets.mk:170: arch/arm/src/libarch.a] Error 2
 make: Target 'all' not remade because of errors.

Signed-off-by: wangzhi16 <wangzhi16@xiaomi.com>