arch/risc-v: Fix the compilation error.
common/riscv_addrenv_kstack.c: In function 'up_addrenv_kstackalloc':
common/riscv_addrenv_kstack.c:68:34: error: 'TLS_STACK_ALIGN' undeclared (first use in this function)
   68 |   tcb->xcp.kstack = kmm_memalign(STACK_ALIGNMENT, ARCH_KERNEL_STACKSIZE);
      |                                  ^~~~~~~~~~~~~~~
common/riscv_addrenv_kstack.c:68:34: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:142: riscv_addrenv_kstack.o] Error 1
make[1]: Target 'libkarch.a' not remade because of errors.
make: *** [tools/LibTargets.mk:59: arch/risc-v/src/libkarch.a] Error 2
make: Target 'all' not remade because of errors.

Signed-off-by: v-tangmeng <v-tangmeng@xiaomi.com>