nxgdb/memdump: fix regular expression for byte sequence
Use pythons' built-in bytes.find instead of re since the it treats value as string representation.
This fixed the issue of

memfind 0x3c452838
Searching for pattern b'3828453c' in memory
Error: missing ), unterminated subpattern at position 1
Traceback (most recent call last):
  File "/home/neo/.local/lib/python3.10/site-packages/nxgdb/utils.py", line 361, in wrapper
    func(self, args, from_tty)
  File "/home/neo/.local/lib/python3.10/site-packages/nxgdb/memdump.py", line 1088, in invoke
    pattern = re.compile(re.escape(value))
  File "/usr/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 843, in _parse
    raise source.error("missing ), unterminated subpattern",
re.error: missing ), unterminated subpattern at position 1

Signed-off-by: xuxingliang <xuxingliang@xiaomi.com>