aio_error: fix ret of aio_error function
A call to aio_error()may return -1 and set errno to EINVAL if
aiocbp does not refer to an operation whose return status has not
yet been retrieved. A call to aio_read() and aio_write() may return -1 and set errno to EINVAL if the criteria is not met. And in aio_read() and aio_write(), aio_result should be set so that aio_error() function can query correctly.

Signed-off-by: tengshuangshuang <tengshuangshuang@xiaomi.com>