nrf53/serial: always compile nrf53_serial.c
So the up_putc function gets defined, just like most of other arch.

Fixed compile error:
nuttx/arch/arm/src/common/arm_nputs.c:44:(.text.up_nputs+0x12): undefined reference to `up_putc'

Signed-off-by: v-tangmeng <v-tangmeng@xiaomi.com>